---
deployment:
  tasks:
    - export DEPLOYPATH=/home/triadtec/finance/
    - source /home/triadtec/nodevenv/repositories/HomeFinance/24/bin/activate && cd /home/HomeFinance/
    - npm install
    - npm run build
    - /bin/cp -R dist/* $DEPLOYPATH